name: Run on beater

on:
  push:


jobs:
  simple-hello:
    runs-on: beater
    container:
      image: pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime
      options:
        --gpus all
    steps:
      - name: Check runtime env
        run: |
          echo "Running on ${{ runner.os }}"
          pwd -P
          whoami

      - name: Check GPU
        run: |
          nvidia-smi


  